version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: transformafacil-db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_admin
      POSTGRES_DB: transformafacil_db
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
