[build]
installCommand = "cd backend && npm install"
buildCommand = "cd backend && npx prisma generate && npm run build"

[start]
command = "cd backend && node dist/index.js"

[variables]
DATABASE_URL = "postgresql://dummy:dummy@localhost:5432/dummy"
