
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const SystemAudit = async (): Promise<string> => {
    const reportLines: string[] = [];
    reportLines.push(`# REPORTE DE ESTADO DEL SISTEMA`);
    reportLines.push(`Fecha: ${new Date().toLocaleString('es-UY')}`);
    reportLines.push(`Generated by: Auto-Auditing Module v1.0`);
    reportLines.push(`---`);

    try {
        // 1. Vehicles
        const vehicleCount = await prisma.vehicle.count();
        reportLines.push(`## 1. Auditoría de Flota`);
        reportLines.push(`- **Total Vehículos**: ${vehicleCount}`);
        if (vehicleCount < 50) {
            reportLines.push(`⚠️ **ALERTA**: La flota registrada es menor a la esperada (50+). Posible falta de sincronización.`);
        } else {
            reportLines.push(`✅ Tamaño de flota saludable.`);
        }

        // 2. Routes & Variants
        const routeCount = await prisma.route.count();
        const variantCount = await prisma.routeVariant.count();
        reportLines.push(`\n## 2. Red de Rutas`);
        reportLines.push(`- **Rutas Maestras**: ${routeCount}`);
        reportLines.push(`- **Variantes Activas**: ${variantCount}`);

        // Specific Check for Route 306 (Reference)
        const route306 = await prisma.route.findFirst({ where: { name: '306' }, include: { variants: true } });
        if (route306) {
            reportLines.push(`- **Ruta 306**: DETECTADA ✅`);
            reportLines.push(`  - Variantes Asociadas: ${route306.variants.length}`);
            route306.variants.forEach(v => {
                reportLines.push(`    - [${v.id}] ${v.name} -> ${v.destination}`);
            });
            if (route306.variants.length === 0) {
                reportLines.push(`  ❌ **ERROR**: La Ruta 306 existe pero no tiene variantes vinculadas.`);
            }
        } else {
            reportLines.push(`- **Ruta 306**: ❌ NO ENCONTRADA (Crítico para pruebas)`);
        }

        // 3. Trip Schedules Data Integrity
        const trips = await prisma.tripSchedule.findMany({ select: { id: true, startTime: true, variantId: true } });
        let badTimeFormat = 0;
        let nullVariant = 0;

        trips.forEach(t => {
            if (!t.startTime || !/^\d{1,2}:\d{2}$/.test(t.startTime)) {
                badTimeFormat++;
            }
            if (!t.variantId) nullVariant++;
        });

        reportLines.push(`\n## 3. Integridad de Horarios (Cartones)`);
        reportLines.push(`- **Total Viajes Programados**: ${trips.length}`);

        if (badTimeFormat > 0) {
            reportLines.push(`❌ **ERROR**: ${badTimeFormat} viajes tienen un formato de hora inválido o vacío. Revisar parser.`);
        } else {
            reportLines.push(`✅ Formato de horas validado (HH:MM).`);
        }

        if (nullVariant > 0) {
            reportLines.push(`❌ **FATAL**: ${nullVariant} viajes huérfanos sin Variante asignada.`);
        }

        // 4. Sequence Integrity
        const emptyVariants = await prisma.routeVariant.findMany({
            where: { sequences: { none: {} } },
            select: { name: true }
        });

        if (emptyVariants.length > 0) {
            reportLines.push(`\n⚠️ **ADVERTENCIA**: Las siguientes variantes no tienen secuencia de paradas definidas:`);
            emptyVariants.forEach(v => reportLines.push(`  - ${v.name}`));
        } else {
            reportLines.push(`\n✅ Todas las variantes tienen secuencias de ruta definidas.`);
        }

    } catch (e) {
        reportLines.push(`\n❌ CRITICAL SYSTEM ERROR DURING AUDIT: ${e}`);
    }

    reportLines.push(`\n---\n*Fin del Reporte*`);
    return reportLines.join('\n');
};
