/**
 * seedUcotCompleto.ts
 * Seed completo UCOT: flota, cartones, personal, coche_personal, programacion_semanal
 * Generado desde FLOTA1-1.docx + Cartones*.xls + Distribucion fin de semana 12-13/04/2026
 */
import {
  doc, writeBatch, collection, addDoc, setDoc, serverTimestamp
} from '../config/firestoreShim';
import { db } from '../config/firebase';

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function runBatches(items: Array<() => void>, label: string, batchSize = 400) {
  let b = writeBatch(db);
  let count = 0;
  for (const fn of items) {
    fn();
    count++;
    if (count % batchSize === 0) {
      await b.commit();
      b = writeBatch(db);
      console.log(`  ${label}: ${count} escritos...`);
    }
  }
  if (count % batchSize !== 0) await b.commit();
  console.log(`  [OK] ${label}: ${count} total`);
}

// ─── Seed Flota (257 vehículos) ──────────────────────────────────────────────

export async function seedFlota() {
  console.log('🚌 [SEED] Flota...');
  const ops: Array<() => void> = [];
  const b = writeBatch(db);
  const vehiculos = [
    { coche: '1', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '2', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '3', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '4', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '5', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '6', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '7', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '8', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '9', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '10', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '11', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '12', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '13', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '14', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '15', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '16', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '17', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '18', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '19', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '20', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '21', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '22', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '23', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '24', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '25', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '26', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '27', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '28', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '29', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '30', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '31', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '32', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '33', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '34', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '35', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '36', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '37', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '38', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '39', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '40', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '41', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '42', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '43', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '44', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '45', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '46', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '47', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '48', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '49', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '50', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '51', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '52', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '53', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '54', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '55', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '56', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '57', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '58', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '59', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '60', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '61', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '62', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '63', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '64', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '65', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '66', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '67', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '68', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '69', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '70', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '71', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '72', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '73', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '74', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '75', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '76', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '77', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '78', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '79', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '80', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '81', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '82', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '83', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '84', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '85', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '86', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '87', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '88', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '89', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '90', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '91', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '92', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '93', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '94', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '95', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '96', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '97', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '98', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '99', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '100', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '101', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '102', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '103', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '104', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '105', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '106', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '107', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '108', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '109', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '110', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '111', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '112', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '113', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '114', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '115', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '116', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '117', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '118', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '119', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '120', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '121', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '122', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '123', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '124', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '125', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '126', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '127', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '128', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '129', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '130', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '131', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '132', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '133', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '134', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '135', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '136', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '137', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '138', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '139', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '140', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '141', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '142', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '143', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '144', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '145', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '146', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '147', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '148', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '149', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '150', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '151', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '152', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '153', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '154', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '155', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '156', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '157', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '158', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '159', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '160', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '161', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '162', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '163', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '164', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '165', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '166', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '167', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '168', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '169', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '201', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '202', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '203', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '204', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '205', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '206', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '207', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '208', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '209', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '210', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '211', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '212', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '213', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '214', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '215', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '221', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '222', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '223', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '224', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '226', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '228', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '230', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '231', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '232', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '233', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '234', marca: 'Mercedes Benz', tipoFlota: 'normal' },
    { coche: '235', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '236', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '237', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '238', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '239', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '240', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '241', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '242', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '243', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '244', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '245', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '246', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '247', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '248', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '249', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '250', marca: 'Agrale', tipoFlota: 'normal' },
    { coche: '251', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '252', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '253', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '254', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '255', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '256', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '257', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '258', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '259', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '260', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '261', marca: 'Agrale-Cummins', tipoFlota: 'normal' },
    { coche: '262', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '263', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '264', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '265', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '266', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '267', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '268', marca: 'Yutong', tipoFlota: 'yutong' },
    { coche: '903', marca: 'Mitsubishi', tipoFlota: 'expendedora' },
    { coche: '909', marca: 'Fiat', tipoFlota: 'expendedora' },
    { coche: '912', marca: 'Mitsubishi', tipoFlota: 'expendedora' },
    { coche: '915', marca: 'Volkswagen', tipoFlota: 'expendedora' },
    { coche: '916', marca: 'Fiat', tipoFlota: 'expendedora' },
    { coche: '917', marca: 'Fiat', tipoFlota: 'expendedora' },
    { coche: '918', marca: 'Volkswagen', tipoFlota: 'expendedora' },
    { coche: '919', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '920', marca: 'Fiat', tipoFlota: 'expendedora' },
    { coche: '921', marca: 'Volkswagen', tipoFlota: 'expendedora' },
    { coche: '922', marca: 'Volkswagen', tipoFlota: 'expendedora' },
    { coche: '923', marca: 'Byd', tipoFlota: 'aire_baterias' },
    { coche: '924', marca: 'Byd', tipoFlota: 'aire_baterias' },
    { coche: '925', marca: 'Byd', tipoFlota: 'aire_baterias' },
    { coche: '926', marca: 'Byd', tipoFlota: 'aire_baterias' },
    { coche: '927', marca: 'Byd', tipoFlota: 'aire_baterias' },
    { coche: '1009', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1014', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1016', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1021', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1050', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1053', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1055', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1057', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1064', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1096', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1098', marca: 'Volvo', tipoFlota: 'normal' },
    { coche: '1110', marca: 'Volvo', tipoFlota: 'normal' },
  ] as const;

  let batch = writeBatch(db);
  let n = 0;
  for (const v of vehiculos) {
    const ref = doc(db, 'vehiculos', v.coche);
    batch.set(ref, {
      id: v.coche,
      internalNumber: v.coche,
      marca: v.marca,
      tipoFlota: v.tipoFlota,
      estado_operativo: 'ACTIVO',
      activo: true,
      agencyId: 70,
      empresa: 70,
      updatedAt: new Date().toISOString(),
    }, { merge: true });
    n++;
    if (n % 400 === 0) { await batch.commit(); batch = writeBatch(db); }
  }
  await batch.commit();
  console.log('[OK] Flota:', vehiculos.length, 'vehiculos');
}

// ─── Seed Cartones (298 cartones) ────────────────────────────────────────────

export async function seedCartones() {
  console.log('📋 [SEED] Cartones...');
  const cartones = [
    { carton: '1000', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:14' },
    { carton: '1001', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:35' },
    { carton: '1003', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1004', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:34' },
    { carton: '1006', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1007', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1008', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1009', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1011', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:21' },
    { carton: '1012', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1014', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1015', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:54' },
    { carton: '1016', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:44' },
    { carton: '1017', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '13:34' },
    { carton: '1018', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '07:16' },
    { carton: '1019', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1020', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1021', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1023', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1024', linea: '329', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1025', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:30' },
    { carton: '1026', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1028', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1029', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:47' },
    { carton: '1030', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1032', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:05' },
    { carton: '1033', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '07:20' },
    { carton: '1034', linea: '329', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1035', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1037', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1038', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:03' },
    { carton: '1039', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1041', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:41' },
    { carton: '1042', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:24' },
    { carton: '1043', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:45' },
    { carton: '1044', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:55' },
    { carton: '1046', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1047', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:36' },
    { carton: '1048', linea: '329', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:57' },
    { carton: '1049', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '07:35' },
    { carton: '1050', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1051', linea: '329', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1052', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '15:40' },
    { carton: '1053', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1054', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:14' },
    { carton: '1056', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1057', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1058', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1059', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1061', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1062', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1063', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1065', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1066', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1067', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1068', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1069', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1070', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1072', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1073', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1074', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:11' },
    { carton: '1075', linea: '328', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1076', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1077', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1078', linea: '329', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1079', linea: '330', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1080', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1081', linea: '329', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1082', linea: '328', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1084', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1085', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1086', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1087', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1088', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1089', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1090', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1091', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1092', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1101', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1102', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1103', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1104', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1105', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1106', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1107', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1108', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1109', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '04:58' },
    { carton: '1110', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1111', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1112', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1113', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1114', linea: '330', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1116', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1117', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1118', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1119', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1120', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1121', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1122', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1123', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1124', linea: '328', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1125', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1126', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1127', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1128', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1129', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1131', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1132', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1133', linea: '329', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1134', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1135', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1137', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1138', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1139', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1140', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1141', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '07:05' },
    { carton: '1142', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1143', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1144', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1145', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1146', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1147', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1148', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1149', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1150', linea: '330', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1151', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1152', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1153', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1154', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1155', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1156', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1157', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1158', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1159', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1160', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1161', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1163', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1164', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1165', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1166', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1167', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1168', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1169', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1170', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1171', linea: '370', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1172', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1178', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1179', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1181', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1182', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1183', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1184', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1190', linea: '221', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1191', linea: '221', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1192', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:53' },
    { carton: '1193', linea: '221', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '09:29' },
    { carton: '1194', linea: '221', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1195', linea: '221', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1196', linea: '221', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1197', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:17' },
    { carton: '1198', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1199', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1201', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1202', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1203', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1204', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6001', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6002', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6003', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6004', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6005', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6006', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6007', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6008', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6009', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6010', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '6011', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1020N', linea: '306', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1038N', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1043N', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1048N', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1056N', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1084N', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1146N', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1154N', linea: '300', tipo: 'habil', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2200', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2201', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2203', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2204', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2206', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2210', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2211', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2212', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2213', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '10:55' },
    { carton: '2214', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '09:40' },
    { carton: '2215', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2216', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2217', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2218', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2219', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '08:39' },
    { carton: '2220', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '10:18' },
    { carton: '2221', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2222', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '08:51' },
    { carton: '2223', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2224', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2225', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2226', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2227', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2228', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:50' },
    { carton: '2229', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2230', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2231', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2233', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2234', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2235', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2236', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2237', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:28' },
    { carton: '2238', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2239', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2240', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2241', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '09:03' },
    { carton: '2242', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2243', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2245', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2246', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2247', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2248', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2249', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2250', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2251', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2252', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2253', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2254', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2255', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2256', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2257', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2258', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2259', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2260', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '07:33' },
    { carton: '2261', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '09:45' },
    { carton: '2262', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2263', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2264', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2265', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '10:15' },
    { carton: '2266', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2267', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2268', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2269', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2270', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2271', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2272', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2273', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2274', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2275', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:49' },
    { carton: '2276', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2277', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2278', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2279', linea: '306', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2280', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2281', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2282', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2283', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2284', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '08:28' },
    { carton: '2285', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2286', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2287', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '07:29' },
    { carton: '2288', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2289', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2290', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2291', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2292', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '08:03' },
    { carton: '2293', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2294', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '05:40' },
    { carton: '2300', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2301', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2302', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2303', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '3590', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '07:05' },
    { carton: '3591', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '3592', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '06:05' },
    { carton: '3593', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '08:53' },
    { carton: '4650', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '4651', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '8501', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '8502', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '8503', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1202', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1503', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '1504', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2100', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2145N', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2160N', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2165N', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2170N', linea: '306', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2175N', linea: '306', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2180N', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2185N', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
    { carton: '2190N', linea: '300', tipo: 'sabado', t1Start: '', t1End: '', t2Start: '', t2End: '', primeraSalida: '' },
  ] as const;

  let batch = writeBatch(db);
  let n = 0;
  for (const c of cartones) {
    const ref = doc(db, 'cartones', c.carton);
    batch.set(ref, {
      id: c.carton,
      serviceNumber: c.carton,
      linea: c.linea,
      tipo: c.tipo,
      t1Start: c.t1Start,
      t1End: c.t1End,
      t2Start: c.t2Start,
      t2End: c.t2End,
      primeraSalida: c.primeraSalida,
      activo: true,
      updatedAt: new Date().toISOString(),
    }, { merge: true });
    n++;
    if (n % 400 === 0) { await batch.commit(); batch = writeBatch(db); }
  }
  await batch.commit();
  console.log('[OK] Cartones:', cartones.length);
}

// ─── Seed Personal (134 conductores) ────────────────────────────────────────

export async function seedPersonal() {
  console.log('👤 [SEED] Personal...');
  const personal = [
    { interno: '12', apellido: 'QUESADA', uid: 'ucot_cond_12' },
    { interno: '13', apellido: 'HERRERA', uid: 'ucot_cond_13' },
    { interno: '24', apellido: 'SONORA', uid: 'ucot_cond_24' },
    { interno: '53', apellido: 'PERDOMO', uid: 'ucot_cond_53' },
    { interno: '35', apellido: 'GONZALEZ', uid: 'ucot_cond_35' },
    { interno: '47', apellido: 'FERREIRA', uid: 'ucot_cond_47' },
    { interno: '58', apellido: 'GONZALEZ', uid: 'ucot_cond_58' },
    { interno: '66', apellido: 'BARCIA', uid: 'ucot_cond_66' },
    { interno: '72', apellido: 'ESCOBAR', uid: 'ucot_cond_72' },
    { interno: '71', apellido: 'CORREA', uid: 'ucot_cond_71' },
    { interno: '74', apellido: 'FERREIRA', uid: 'ucot_cond_74' },
    { interno: '80', apellido: 'PINA', uid: 'ucot_cond_80' },
    { interno: '83', apellido: 'SOPREDERO', uid: 'ucot_cond_83' },
    { interno: '86', apellido: 'OLIVAR', uid: 'ucot_cond_86' },
    { interno: '90', apellido: 'BRAGA', uid: 'ucot_cond_90' },
    { interno: '93', apellido: 'LOPEZ', uid: 'ucot_cond_93' },
    { interno: '97', apellido: 'SANGIOVANNI', uid: 'ucot_cond_97' },
    { interno: '121', apellido: 'FERREIRA', uid: 'ucot_cond_121' },
    { interno: '129', apellido: 'BOGA', uid: 'ucot_cond_129' },
    { interno: '136', apellido: 'VHEITZ', uid: 'ucot_cond_136' },
    { interno: '144', apellido: 'RODRIGUEZ', uid: 'ucot_cond_144' },
    { interno: '143', apellido: 'PERAZZA', uid: 'ucot_cond_143' },
    { interno: '153', apellido: 'RICCO', uid: 'ucot_cond_153' },
    { interno: '170', apellido: 'SANCHEZ', uid: 'ucot_cond_170' },
    { interno: '171', apellido: 'GUTIERREZ', uid: 'ucot_cond_171' },
    { interno: '177', apellido: 'FITOS', uid: 'ucot_cond_177' },
    { interno: '186', apellido: 'FERREIRA', uid: 'ucot_cond_186' },
    { interno: '196', apellido: 'CANCELA', uid: 'ucot_cond_196' },
    { interno: '198', apellido: 'MONTGOMERY', uid: 'ucot_cond_198' },
    { interno: '231', apellido: 'SONORA', uid: 'ucot_cond_231' },
    { interno: '237', apellido: 'MODERNELL', uid: 'ucot_cond_237' },
    { interno: '325', apellido: 'GARZABAL', uid: 'ucot_cond_325' },
    { interno: '401', apellido: 'AROCENA', uid: 'ucot_cond_401' },
    { interno: '410', apellido: 'PENA', uid: 'ucot_cond_410' },
    { interno: '421', apellido: 'BERMONDS', uid: 'ucot_cond_421' },
    { interno: '422', apellido: 'RENTANCOR', uid: 'ucot_cond_422' },
    { interno: '628', apellido: 'NUNEZ', uid: 'ucot_cond_628' },
    { interno: '623', apellido: 'RAMOS', uid: 'ucot_cond_623' },
    { interno: '627', apellido: 'LORENZI', uid: 'ucot_cond_627' },
    { interno: '652', apellido: 'DELGADO', uid: 'ucot_cond_652' },
    { interno: '653', apellido: 'CALDERON', uid: 'ucot_cond_653' },
    { interno: '677', apellido: 'CABRERA', uid: 'ucot_cond_677' },
    { interno: '692', apellido: 'RICARTE', uid: 'ucot_cond_692' },
    { interno: '705', apellido: 'DI LEONE', uid: 'ucot_cond_705' },
    { interno: '706', apellido: 'GOMEZ', uid: 'ucot_cond_706' },
    { interno: '711', apellido: 'PROBABBUENA', uid: 'ucot_cond_711' },
    { interno: '723', apellido: 'RODRIGUEZ', uid: 'ucot_cond_723' },
    { interno: '724', apellido: 'PEREZ', uid: 'ucot_cond_724' },
    { interno: '726', apellido: 'ANDRADE', uid: 'ucot_cond_726' },
    { interno: '730', apellido: 'SOUMANO', uid: 'ucot_cond_730' },
    { interno: '735', apellido: 'FERNANDEZ', uid: 'ucot_cond_735' },
    { interno: '740', apellido: 'SUAREZ', uid: 'ucot_cond_740' },
    { interno: '742', apellido: 'ESCUDERO', uid: 'ucot_cond_742' },
    { interno: '776', apellido: 'CABRERA', uid: 'ucot_cond_776' },
    { interno: '777', apellido: 'MOLINARI', uid: 'ucot_cond_777' },
    { interno: '788', apellido: 'ZERBO', uid: 'ucot_cond_788' },
    { interno: '810', apellido: 'PINOS', uid: 'ucot_cond_810' },
    { interno: '825', apellido: 'FERNANDEZ', uid: 'ucot_cond_825' },
    { interno: '857', apellido: 'LAGOS', uid: 'ucot_cond_857' },
    { interno: '858', apellido: 'CACERES', uid: 'ucot_cond_858' },
    { interno: '890', apellido: 'FERREIRA', uid: 'ucot_cond_890' },
    { interno: '904', apellido: 'FERRARO', uid: 'ucot_cond_904' },
    { interno: '906', apellido: 'ALONSO', uid: 'ucot_cond_906' },
    { interno: '912', apellido: 'RECALDE', uid: 'ucot_cond_912' },
    { interno: '914', apellido: 'SAMPIL', uid: 'ucot_cond_914' },
    { interno: '3000', apellido: 'MARTINEZ', uid: 'ucot_cond_3000' },
    { interno: '3007', apellido: 'MARTINEZ', uid: 'ucot_cond_3007' },
    { interno: '3009', apellido: 'AGUERRE', uid: 'ucot_cond_3009' },
    { interno: '3015', apellido: 'PEREZ', uid: 'ucot_cond_3015' },
    { interno: '3017', apellido: 'FRANCO', uid: 'ucot_cond_3017' },
    { interno: '3038', apellido: 'SALINAS', uid: 'ucot_cond_3038' },
    { interno: '3043', apellido: 'DIAZ', uid: 'ucot_cond_3043' },
    { interno: '3048', apellido: 'MUSTO', uid: 'ucot_cond_3048' },
    { interno: '3049', apellido: 'ROSA', uid: 'ucot_cond_3049' },
    { interno: '3064', apellido: 'RODAS', uid: 'ucot_cond_3064' },
    { interno: '3090', apellido: 'TABAREZ', uid: 'ucot_cond_3090' },
    { interno: '3093', apellido: 'CRUZ', uid: 'ucot_cond_3093' },
    { interno: '3098', apellido: 'GONZALEZ', uid: 'ucot_cond_3098' },
    { interno: '3102', apellido: 'LAMBION', uid: 'ucot_cond_3102' },
    { interno: '1104', apellido: 'DO AMARAL', uid: 'ucot_cond_1104' },
    { interno: '1105', apellido: 'GIMENEZ', uid: 'ucot_cond_1105' },
    { interno: '3110', apellido: 'PAZ', uid: 'ucot_cond_3110' },
    { interno: '3111', apellido: 'PANIZZA', uid: 'ucot_cond_3111' },
    { interno: '3112', apellido: 'PEREZ', uid: 'ucot_cond_3112' },
    { interno: '3122', apellido: 'GARRIDO', uid: 'ucot_cond_3122' },
    { interno: '3130', apellido: 'RUIZ', uid: 'ucot_cond_3130' },
    { interno: '3138', apellido: 'GUEVARA', uid: 'ucot_cond_3138' },
    { interno: '3141', apellido: 'DIAZ', uid: 'ucot_cond_3141' },
    { interno: '3150', apellido: 'PENA', uid: 'ucot_cond_3150' },
    { interno: '3160', apellido: 'PINEIRO', uid: 'ucot_cond_3160' },
    { interno: '8258', apellido: 'MARTINEZ', uid: 'ucot_cond_8258' },
    { interno: '120', apellido: 'DE PATTI', uid: 'ucot_cond_120' },
    { interno: '611', apellido: 'FRANCO', uid: 'ucot_cond_611' },
    { interno: '793', apellido: 'DIAZ', uid: 'ucot_cond_793' },
    { interno: '837', apellido: 'SOLER', uid: 'ucot_cond_837' },
    { interno: '3003', apellido: 'HUQUE', uid: 'ucot_cond_3003' },
    { interno: '15', apellido: 'RODRIGUEZ', uid: 'ucot_cond_15' },
    { interno: '18', apellido: 'FERREIRA', uid: 'ucot_cond_18' },
    { interno: '50', apellido: 'BACTERINCA', uid: 'ucot_cond_50' },
    { interno: '64', apellido: 'VAZQUEZ', uid: 'ucot_cond_64' },
    { interno: '73', apellido: 'CORREA', uid: 'ucot_cond_73' },
    { interno: '80', apellido: 'OLIVAR', uid: 'ucot_cond_80' },
    { interno: '102', apellido: 'BURGUEZ', uid: 'ucot_cond_102' },
    { interno: '107', apellido: 'AGUIRRE', uid: 'ucot_cond_107' },
    { interno: '115', apellido: 'MACLLIO', uid: 'ucot_cond_115' },
    { interno: '133', apellido: 'LOZANO', uid: 'ucot_cond_133' },
    { interno: '135', apellido: 'BOGA', uid: 'ucot_cond_135' },
    { interno: '135', apellido: 'OLIVERA', uid: 'ucot_cond_135' },
    { interno: '135', apellido: 'LANDONI', uid: 'ucot_cond_135' },
    { interno: '134', apellido: 'VHEITZ', uid: 'ucot_cond_134' },
    { interno: '163', apellido: 'RICCO', uid: 'ucot_cond_163' },
    { interno: '183', apellido: 'MONTES', uid: 'ucot_cond_183' },
    { interno: '199', apellido: 'BARRERA', uid: 'ucot_cond_199' },
    { interno: '217', apellido: 'SONORA', uid: 'ucot_cond_217' },
    { interno: '217', apellido: 'MODERNELL', uid: 'ucot_cond_217' },
    { interno: '317', apellido: 'IRIEZ', uid: 'ucot_cond_317' },
    { interno: '217', apellido: 'GALAZABAL', uid: 'ucot_cond_217' },
    { interno: '222', apellido: 'AQUA', uid: 'ucot_cond_222' },
    { interno: '234', apellido: 'LUPENA', uid: 'ucot_cond_234' },
    { interno: '234', apellido: 'MELOGNO', uid: 'ucot_cond_234' },
    { interno: '414', apellido: 'MARTORANO', uid: 'ucot_cond_414' },
    { interno: '519', apellido: 'REQUEIRA', uid: 'ucot_cond_519' },
    { interno: '502', apellido: 'NOVA', uid: 'ucot_cond_502' },
    { interno: '506', apellido: 'SILVA', uid: 'ucot_cond_506' },
    { interno: '518', apellido: 'MARQUEZ', uid: 'ucot_cond_518' },
    { interno: '534', apellido: 'REQUERA', uid: 'ucot_cond_534' },
    { interno: '653', apellido: 'DELGADO', uid: 'ucot_cond_653' },
    { interno: '655', apellido: 'FERREYA', uid: 'ucot_cond_655' },
    { interno: '665', apellido: 'MOREIRA', uid: 'ucot_cond_665' },
    { interno: '711', apellido: 'ALTEZ', uid: 'ucot_cond_711' },
    { interno: '724', apellido: 'RODRIGUEZ', uid: 'ucot_cond_724' },
    { interno: '730', apellido: 'LOPEZ', uid: 'ucot_cond_730' },
    { interno: '782', apellido: 'LARROSA', uid: 'ucot_cond_782' },
    { interno: '854', apellido: 'COSTA', uid: 'ucot_cond_854' },
  ] as const;

  let batch = writeBatch(db);
  let n = 0;
  for (const p of personal) {
    const ref = doc(db, 'users', p.uid);
    batch.set(ref, {
      uid: p.uid,
      internalNumber: p.interno,
      lastName: p.apellido,
      fullName: p.apellido,
      rol: 'CONDUCTOR',
      roles: ['CONDUCTOR'],
      activo: true,
      updatedAt: new Date().toISOString(),
    }, { merge: true });
    n++;
    if (n % 400 === 0) { await batch.commit(); batch = writeBatch(db); }
  }
  await batch.commit();
  console.log('[OK] Personal:', personal.length);
}

// ─── Seed CochePersonal (78 coches con personal) ────────────────────────────

export async function seedCochePersonal() {
  console.log('🚌👤 [SEED] CochePersonal...');
  const cochePersonalData = [
    { cocheInternalNumber: '4', personal: [{ userId: 'ucot_cond_3112', internalNumber: '3112', fullName: 'PEREZ', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_837', internalNumber: '837', fullName: 'SOLER', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '5', personal: [{ userId: 'ucot_cond_64', internalNumber: '64', fullName: 'VAZQUEZ', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_102', internalNumber: '102', fullName: 'BURGUEZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '9', personal: [{ userId: 'ucot_cond_120', internalNumber: '120', fullName: 'DE PATTI', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_217', internalNumber: '217', fullName: 'GALAZABAL', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '10', personal: [{ userId: 'ucot_cond_730', internalNumber: '730', fullName: 'SOUMANO', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '12', personal: [{ userId: 'ucot_cond_422', internalNumber: '422', fullName: 'RENTANCOR', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '14', personal: [{ userId: 'ucot_cond_134', internalNumber: '134', fullName: 'VHEITZ', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_782', internalNumber: '782', fullName: 'LARROSA', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '15', personal: [{ userId: 'ucot_cond_740', internalNumber: '740', fullName: 'SUAREZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '16', personal: [{ userId: 'ucot_cond_793', internalNumber: '793', fullName: 'DIAZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '18', personal: [{ userId: 'ucot_cond_611', internalNumber: '611', fullName: 'FRANCO', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_199', internalNumber: '199', fullName: 'BARRERA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '19', personal: [{ userId: 'ucot_cond_623', internalNumber: '623', fullName: 'RAMOS', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_825', internalNumber: '825', fullName: 'FERNANDEZ', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_724', internalNumber: '724', fullName: 'RODRIGUEZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '21', personal: [{ userId: 'ucot_cond_24', internalNumber: '24', fullName: 'SONORA', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_810', internalNumber: '810', fullName: 'PINOS', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '22', personal: [{ userId: 'ucot_cond_677', internalNumber: '677', fullName: 'CABRERA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '24', personal: [{ userId: 'ucot_cond_788', internalNumber: '788', fullName: 'ZERBO', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '27', personal: [{ userId: 'ucot_cond_518', internalNumber: '518', fullName: 'MARQUEZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '29', personal: [{ userId: 'ucot_cond_3003', internalNumber: '3003', fullName: 'HUQUE', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_50', internalNumber: '50', fullName: 'BACTERINCA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '30', personal: [{ userId: 'ucot_cond_3015', internalNumber: '3015', fullName: 'PEREZ', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_3017', internalNumber: '3017', fullName: 'FRANCO', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '36', personal: [{ userId: 'ucot_cond_705', internalNumber: '705', fullName: 'DI LEONE', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '38', personal: [{ userId: 'ucot_cond_3150', internalNumber: '3150', fullName: 'PENA', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_414', internalNumber: '414', fullName: 'MARTORANO', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '39', personal: [{ userId: 'ucot_cond_857', internalNumber: '857', fullName: 'LAGOS', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '40', personal: [{ userId: 'ucot_cond_627', internalNumber: '627', fullName: 'LORENZI', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '41', personal: [{ userId: 'ucot_cond_222', internalNumber: '222', fullName: 'AQUA', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_854', internalNumber: '854', fullName: 'COSTA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '42', personal: [{ userId: 'ucot_cond_170', internalNumber: '170', fullName: 'SANCHEZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '48', personal: [{ userId: 'ucot_cond_47', internalNumber: '47', fullName: 'FERREIRA', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_183', internalNumber: '183', fullName: 'MONTES', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '55', personal: [{ userId: 'ucot_cond_58', internalNumber: '58', fullName: 'GONZALEZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '56', personal: [{ userId: 'ucot_cond_706', internalNumber: '706', fullName: 'GOMEZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '57', personal: [{ userId: 'ucot_cond_776', internalNumber: '776', fullName: 'CABRERA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '58', personal: [{ userId: 'ucot_cond_421', internalNumber: '421', fullName: 'BERMONDS', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '59', personal: [{ userId: 'ucot_cond_422', internalNumber: '422', fullName: 'RENTANCOR', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_711', internalNumber: '711', fullName: 'PROBABBUENA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '60', personal: [{ userId: 'ucot_cond_80', internalNumber: '80', fullName: 'PINA', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_735', internalNumber: '735', fullName: 'FERNANDEZ', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_1104', internalNumber: '1104', fullName: 'DO AMARAL', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '65', personal: [{ userId: 'ucot_cond_3098', internalNumber: '3098', fullName: 'GONZALEZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '67', personal: [{ userId: 'ucot_cond_129', internalNumber: '129', fullName: 'BOGA', turnoBase: 3 as 1|2, esFijo: false }, { userId: 'ucot_cond_3049', internalNumber: '3049', fullName: 'ROSA', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_12', internalNumber: '12', fullName: 'QUESADA', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '68', personal: [{ userId: 'ucot_cond_3007', internalNumber: '3007', fullName: 'MARTINEZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '69', personal: [{ userId: 'ucot_cond_912', internalNumber: '912', fullName: 'RECALDE', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '72', personal: [{ userId: 'ucot_cond_171', internalNumber: '171', fullName: 'GUTIERREZ', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_858', internalNumber: '858', fullName: 'CACERES', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_653', internalNumber: '653', fullName: 'DELGADO', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '74', personal: [{ userId: 'ucot_cond_325', internalNumber: '325', fullName: 'GARZABAL', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '75', personal: [{ userId: 'ucot_cond_135', internalNumber: '135', fullName: 'OLIVERA', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '77', personal: [{ userId: 'ucot_cond_3160', internalNumber: '3160', fullName: 'PINEIRO', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '79', personal: [{ userId: 'ucot_cond_177', internalNumber: '177', fullName: 'FITOS', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '80', personal: [{ userId: 'ucot_cond_135', internalNumber: '135', fullName: 'BOGA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '82', personal: [{ userId: 'ucot_cond_73', internalNumber: '73', fullName: 'CORREA', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_655', internalNumber: '655', fullName: 'FERREYA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '90', personal: [{ userId: 'ucot_cond_135', internalNumber: '135', fullName: 'LANDONI', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_234', internalNumber: '234', fullName: 'MELOGNO', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '95', personal: [{ userId: 'ucot_cond_3102', internalNumber: '3102', fullName: 'LAMBION', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_97', internalNumber: '97', fullName: 'SANGIOVANNI', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '96', personal: [{ userId: 'ucot_cond_914', internalNumber: '914', fullName: 'SAMPIL', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '97', personal: [{ userId: 'ucot_cond_3111', internalNumber: '3111', fullName: 'PANIZZA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '100', personal: [{ userId: 'ucot_cond_3064', internalNumber: '3064', fullName: 'RODAS', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '102', personal: [{ userId: 'ucot_cond_115', internalNumber: '115', fullName: 'MACLLIO', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '107', personal: [{ userId: 'ucot_cond_906', internalNumber: '906', fullName: 'ALONSO', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_133', internalNumber: '133', fullName: 'LOZANO', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '108', personal: [{ userId: 'ucot_cond_742', internalNumber: '742', fullName: 'ESCUDERO', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_234', internalNumber: '234', fullName: 'LUPENA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '109', personal: [{ userId: 'ucot_cond_724', internalNumber: '724', fullName: 'PEREZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '111', personal: [{ userId: 'ucot_cond_3093', internalNumber: '3093', fullName: 'CRUZ', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_80', internalNumber: '80', fullName: 'OLIVAR', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_519', internalNumber: '519', fullName: 'REQUEIRA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '112', personal: [{ userId: 'ucot_cond_153', internalNumber: '153', fullName: 'RICCO', turnoBase: 3 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '113', personal: [{ userId: 'ucot_cond_186', internalNumber: '186', fullName: 'FERREIRA', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '115', personal: [{ userId: 'ucot_cond_890', internalNumber: '890', fullName: 'FERREIRA', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_665', internalNumber: '665', fullName: 'MOREIRA', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '117', personal: [{ userId: 'ucot_cond_196', internalNumber: '196', fullName: 'CANCELA', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_317', internalNumber: '317', fullName: 'IRIEZ', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_788', internalNumber: '788', fullName: 'ZERBO', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '138', personal: [{ userId: 'ucot_cond_730', internalNumber: '730', fullName: 'SOUMANO', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_904', internalNumber: '904', fullName: 'FERRARO', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '141', personal: [{ userId: 'ucot_cond_97', internalNumber: '97', fullName: 'SANGIOVANNI', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '142', personal: [{ userId: 'ucot_cond_401', internalNumber: '401', fullName: 'AROCENA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '144', personal: [{ userId: 'ucot_cond_3138', internalNumber: '3138', fullName: 'GUEVARA', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '150', personal: [{ userId: 'ucot_cond_53', internalNumber: '53', fullName: 'PERDOMO', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '152', personal: [{ userId: 'ucot_cond_410', internalNumber: '410', fullName: 'PENA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '153', personal: [{ userId: 'ucot_cond_3000', internalNumber: '3000', fullName: 'MARTINEZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '155', personal: [{ userId: 'ucot_cond_3130', internalNumber: '3130', fullName: 'RUIZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '156', personal: [{ userId: 'ucot_cond_71', internalNumber: '71', fullName: 'CORREA', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '158', personal: [{ userId: 'ucot_cond_777', internalNumber: '777', fullName: 'MOLINARI', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_15', internalNumber: '15', fullName: 'RODRIGUEZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '161', personal: [{ userId: 'ucot_cond_90', internalNumber: '90', fullName: 'BRAGA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '163', personal: [{ userId: 'ucot_cond_72', internalNumber: '72', fullName: 'ESCOBAR', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_1105', internalNumber: '1105', fullName: 'GIMENEZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '164', personal: [{ userId: 'ucot_cond_35', internalNumber: '35', fullName: 'GONZALEZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '167', personal: [{ userId: 'ucot_cond_237', internalNumber: '237', fullName: 'MODERNELL', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '168', personal: [{ userId: 'ucot_cond_506', internalNumber: '506', fullName: 'SILVA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '176', personal: [{ userId: 'ucot_cond_653', internalNumber: '653', fullName: 'CALDERON', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '189', personal: [{ userId: 'ucot_cond_534', internalNumber: '534', fullName: 'REQUERA', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '201', personal: [{ userId: 'ucot_cond_144', internalNumber: '144', fullName: 'RODRIGUEZ', turnoBase: 2 as 1|2, esFijo: false }, { userId: 'ucot_cond_502', internalNumber: '502', fullName: 'NOVA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '206', personal: [{ userId: 'ucot_cond_3038', internalNumber: '3038', fullName: 'SALINAS', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '207', personal: [{ userId: 'ucot_cond_143', internalNumber: '143', fullName: 'PERAZZA', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_217', internalNumber: '217', fullName: 'MODERNELL', turnoBase: 1 as 1|2, esFijo: false }, { userId: 'ucot_cond_730', internalNumber: '730', fullName: 'LOPEZ', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '268', personal: [{ userId: 'ucot_cond_711', internalNumber: '711', fullName: 'ALTEZ', turnoBase: 1 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '700', personal: [{ userId: 'ucot_cond_217', internalNumber: '217', fullName: 'SONORA', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '1050', personal: [{ userId: 'ucot_cond_3048', internalNumber: '3048', fullName: 'MUSTO', turnoBase: 2 as 1|2, esFijo: false }] },
    { cocheInternalNumber: '1053', personal: [{ userId: 'ucot_cond_3122', internalNumber: '3122', fullName: 'GARRIDO', turnoBase: 1 as 1|2, esFijo: false }] },
  ];

  let batch = writeBatch(db);
  let n = 0;
  for (const cp of cochePersonalData) {
    const ref = doc(db, 'coche_personal', 'cp_' + cp.cocheInternalNumber);
    batch.set(ref, {
      cocheInternalNumber: cp.cocheInternalNumber,
      personal: cp.personal,
      regimen: 'semana_semana',
      bloquesSemana: [],
      activo: true,
      updatedAt: new Date().toISOString(),
    }, { merge: true });
    n++;
    if (n % 400 === 0) { await batch.commit(); batch = writeBatch(db); }
  }
  await batch.commit();
  console.log('[OK] CochePersonal:', cochePersonalData.length, 'coches');
}

// ─── Seed ProgramacionSemanal finde 12-13/04/2026 ───────────────────────────

export async function seedProgramacionSemanal() {
  console.log('📅 [SEED] ProgramacionSemanal 12-13/04/2026...');
  const batch = writeBatch(db);

  // SÁBADO 12/04/2026
  const distSab = [
    { cocheInternalNumber: '67', servicio: '3440', tipoFlota: 'normal' as const, orden: 0 },
    { cocheInternalNumber: '158', servicio: '3400', tipoFlota: 'normal' as const, orden: 1 },
    { cocheInternalNumber: '29', servicio: '3390', tipoFlota: 'normal' as const, orden: 2 },
    { cocheInternalNumber: '5', servicio: '3452', tipoFlota: 'normal' as const, orden: 3 },
    { cocheInternalNumber: '82', servicio: '3451', tipoFlota: 'normal' as const, orden: 4 },
    { cocheInternalNumber: '111', servicio: '3451', tipoFlota: 'normal' as const, orden: 5 },
    { cocheInternalNumber: '95', servicio: '3444', tipoFlota: 'normal' as const, orden: 6 },
    { cocheInternalNumber: '102', servicio: '3441', tipoFlota: 'normal' as const, orden: 7 },
    { cocheInternalNumber: '107', servicio: '3421', tipoFlota: 'normal' as const, orden: 8 },
    { cocheInternalNumber: '80', servicio: '3442', tipoFlota: 'normal' as const, orden: 9 },
    { cocheInternalNumber: '75', servicio: '3442', tipoFlota: 'normal' as const, orden: 10 },
    { cocheInternalNumber: '90', servicio: '3444', tipoFlota: 'normal' as const, orden: 11 },
    { cocheInternalNumber: '14', servicio: '3444', tipoFlota: 'normal' as const, orden: 12 },
    { cocheInternalNumber: '48', servicio: '3426', tipoFlota: 'normal' as const, orden: 13 },
    { cocheInternalNumber: '18', servicio: '3509', tipoFlota: 'normal' as const, orden: 14 },
    { cocheInternalNumber: '700', servicio: '3411', tipoFlota: 'normal' as const, orden: 15 },
    { cocheInternalNumber: '207', servicio: '4591', tipoFlota: 'normal' as const, orden: 16 },
    { cocheInternalNumber: '117', servicio: '3662', tipoFlota: 'normal' as const, orden: 17 },
    { cocheInternalNumber: '9', servicio: '3446', tipoFlota: 'normal' as const, orden: 18 },
    { cocheInternalNumber: '41', servicio: '3435', tipoFlota: 'normal' as const, orden: 19 },
    { cocheInternalNumber: '108', servicio: '3441', tipoFlota: 'normal' as const, orden: 20 },
    { cocheInternalNumber: '38', servicio: '3454', tipoFlota: 'normal' as const, orden: 21 },
    { cocheInternalNumber: '12', servicio: '3107', tipoFlota: 'normal' as const, orden: 22 },
    { cocheInternalNumber: '201', servicio: '4597', tipoFlota: 'normal' as const, orden: 23 },
    { cocheInternalNumber: '168', servicio: '3423', tipoFlota: 'normal' as const, orden: 24 },
    { cocheInternalNumber: '27', servicio: '3445', tipoFlota: 'normal' as const, orden: 25 },
    { cocheInternalNumber: '189', servicio: '3424', tipoFlota: 'normal' as const, orden: 26 },
    { cocheInternalNumber: '72', servicio: '3450', tipoFlota: 'normal' as const, orden: 27 },
    { cocheInternalNumber: '115', servicio: '3461', tipoFlota: 'normal' as const, orden: 28 },
    { cocheInternalNumber: '268', servicio: '3580', tipoFlota: 'normal' as const, orden: 29 },
    { cocheInternalNumber: '19', servicio: '3443', tipoFlota: 'normal' as const, orden: 30 },
    { cocheInternalNumber: '10', servicio: '3170', tipoFlota: 'normal' as const, orden: 31 },
  ];
  batch.set(doc(db, 'programacion_semanal', 'ps_2026-04-12'), {
    fecha: '2026-04-12',
    semanaISO: '2026-W15',
    diaNombre: 'Sabado',
    distribuciones: distSab,
    enMantenimiento: [],
    totalServicios: 32,
    totalParalizas: 0,
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  }, { merge: true });

  // DOMINGO 13/04/2026
  const distDom = [
    { cocheInternalNumber: '21', servicio: '1077', tipoFlota: 'normal' as const, orden: 0 },
    { cocheInternalNumber: '150', servicio: '1160', tipoFlota: 'normal' as const, orden: 1 },
    { cocheInternalNumber: '164', servicio: '1038', tipoFlota: 'normal' as const, orden: 2 },
    { cocheInternalNumber: '48', servicio: '1188', tipoFlota: 'normal' as const, orden: 3 },
    { cocheInternalNumber: '55', servicio: '1007', tipoFlota: 'normal' as const, orden: 4 },
    { cocheInternalNumber: '163', servicio: '1037', tipoFlota: 'normal' as const, orden: 5 },
    { cocheInternalNumber: '156', servicio: '1103', tipoFlota: 'normal' as const, orden: 6 },
    { cocheInternalNumber: '60', servicio: '1067', tipoFlota: 'normal' as const, orden: 7 },
    { cocheInternalNumber: '161', servicio: '1035', tipoFlota: 'normal' as const, orden: 8 },
    { cocheInternalNumber: '141', servicio: '1133', tipoFlota: 'normal' as const, orden: 9 },
    { cocheInternalNumber: '67', servicio: '1126', tipoFlota: 'normal' as const, orden: 10 },
    { cocheInternalNumber: '201', servicio: '1194', tipoFlota: 'normal' as const, orden: 11 },
    { cocheInternalNumber: '207', servicio: '1191', tipoFlota: 'normal' as const, orden: 12 },
    { cocheInternalNumber: '112', servicio: '1106', tipoFlota: 'normal' as const, orden: 13 },
    { cocheInternalNumber: '42', servicio: '1058', tipoFlota: 'normal' as const, orden: 14 },
    { cocheInternalNumber: '72', servicio: '1119', tipoFlota: 'normal' as const, orden: 15 },
    { cocheInternalNumber: '79', servicio: '1125', tipoFlota: 'normal' as const, orden: 16 },
    { cocheInternalNumber: '113', servicio: '1137', tipoFlota: 'normal' as const, orden: 17 },
    { cocheInternalNumber: '117', servicio: '1106', tipoFlota: 'normal' as const, orden: 18 },
    { cocheInternalNumber: '167', servicio: '1041', tipoFlota: 'normal' as const, orden: 19 },
    { cocheInternalNumber: '74', servicio: '1060', tipoFlota: 'normal' as const, orden: 20 },
    { cocheInternalNumber: '142', servicio: '1152', tipoFlota: 'normal' as const, orden: 21 },
    { cocheInternalNumber: '152', servicio: '1113', tipoFlota: 'normal' as const, orden: 22 },
    { cocheInternalNumber: '58', servicio: '1068', tipoFlota: 'normal' as const, orden: 23 },
    { cocheInternalNumber: '59', servicio: '1064', tipoFlota: 'normal' as const, orden: 24 },
    { cocheInternalNumber: '19', servicio: '1046', tipoFlota: 'normal' as const, orden: 25 },
    { cocheInternalNumber: '40', servicio: '1057', tipoFlota: 'normal' as const, orden: 26 },
    { cocheInternalNumber: '176', servicio: '1133', tipoFlota: 'normal' as const, orden: 27 },
    { cocheInternalNumber: '22', servicio: '1133', tipoFlota: 'normal' as const, orden: 28 },
    { cocheInternalNumber: '36', servicio: '1118', tipoFlota: 'normal' as const, orden: 29 },
    { cocheInternalNumber: '56', servicio: '1007', tipoFlota: 'normal' as const, orden: 30 },
    { cocheInternalNumber: '109', servicio: '1104', tipoFlota: 'normal' as const, orden: 31 },
    { cocheInternalNumber: '138', servicio: '1070', tipoFlota: 'normal' as const, orden: 32 },
    { cocheInternalNumber: '15', servicio: '1044', tipoFlota: 'normal' as const, orden: 33 },
    { cocheInternalNumber: '108', servicio: '1103', tipoFlota: 'normal' as const, orden: 34 },
    { cocheInternalNumber: '57', servicio: '1123', tipoFlota: 'normal' as const, orden: 35 },
    { cocheInternalNumber: '158', servicio: '1032', tipoFlota: 'normal' as const, orden: 36 },
    { cocheInternalNumber: '24', servicio: '1004', tipoFlota: 'normal' as const, orden: 37 },
    { cocheInternalNumber: '39', servicio: '1056', tipoFlota: 'normal' as const, orden: 38 },
    { cocheInternalNumber: '115', servicio: '1109', tipoFlota: 'normal' as const, orden: 39 },
    { cocheInternalNumber: '107', servicio: '1171', tipoFlota: 'normal' as const, orden: 40 },
    { cocheInternalNumber: '69', servicio: '1127', tipoFlota: 'normal' as const, orden: 41 },
    { cocheInternalNumber: '96', servicio: '1160', tipoFlota: 'normal' as const, orden: 42 },
    { cocheInternalNumber: '153', servicio: '1137', tipoFlota: 'normal' as const, orden: 43 },
    { cocheInternalNumber: '68', servicio: '1087', tipoFlota: 'normal' as const, orden: 44 },
    { cocheInternalNumber: '30', servicio: '1081', tipoFlota: 'normal' as const, orden: 45 },
    { cocheInternalNumber: '206', servicio: '1199', tipoFlota: 'normal' as const, orden: 46 },
    { cocheInternalNumber: '1050', servicio: '1144', tipoFlota: 'normal' as const, orden: 47 },
    { cocheInternalNumber: '100', servicio: '1073', tipoFlota: 'normal' as const, orden: 48 },
    { cocheInternalNumber: '111', servicio: '1105', tipoFlota: 'normal' as const, orden: 49 },
    { cocheInternalNumber: '65', servicio: '1011', tipoFlota: 'normal' as const, orden: 50 },
    { cocheInternalNumber: '95', servicio: '1157', tipoFlota: 'normal' as const, orden: 51 },
    { cocheInternalNumber: '97', servicio: '1135', tipoFlota: 'normal' as const, orden: 52 },
    { cocheInternalNumber: '4', servicio: '1000', tipoFlota: 'normal' as const, orden: 53 },
    { cocheInternalNumber: '1053', servicio: '1075', tipoFlota: 'normal' as const, orden: 54 },
    { cocheInternalNumber: '155', servicio: '1029', tipoFlota: 'normal' as const, orden: 55 },
    { cocheInternalNumber: '144', servicio: '1158', tipoFlota: 'normal' as const, orden: 56 },
    { cocheInternalNumber: '38', servicio: '1118', tipoFlota: 'normal' as const, orden: 57 },
    { cocheInternalNumber: '77', servicio: '1014', tipoFlota: 'normal' as const, orden: 58 },
    { cocheInternalNumber: '9', servicio: '1009', tipoFlota: 'normal' as const, orden: 59 },
    { cocheInternalNumber: '18', servicio: '1003', tipoFlota: 'normal' as const, orden: 60 },
    { cocheInternalNumber: '16', servicio: '1003', tipoFlota: 'normal' as const, orden: 61 },
    { cocheInternalNumber: '29', servicio: '1006', tipoFlota: 'normal' as const, orden: 62 },
  ];
  batch.set(doc(db, 'programacion_semanal', 'ps_2026-04-13'), {
    fecha: '2026-04-13',
    semanaISO: '2026-W15',
    diaNombre: 'Domingo',
    distribuciones: distDom,
    enMantenimiento: [],
    totalServicios: 63,
    totalParalizas: 0,
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  }, { merge: true });

  await batch.commit();
  console.log('[OK] ProgramacionSemanal: sabado', distSab.length, 'coches | domingo', distDom.length, 'coches');
}

// ─── Seed completo ───────────────────────────────────────────────────────────

export async function seedUcotCompleto() {
  console.log('🚀 [UCOT SEED] Iniciando seed completo...');
  await seedFlota();
  await seedCartones();
  await seedPersonal();
  await seedCochePersonal();
  await seedProgramacionSemanal();
  console.log('✅ [UCOT SEED] Completado!');
}